set_project("flame")
set_languages("c20","c++20")

option("vendor-boost")
    set_default("/data/vendor/boost-1.74")
    after_check(function(option)
        option:add("includedirs","$(vendor-boost)/include")
        option:add("linkdirs","$(vendor-boost)/lib")
    end)

option("vendor-php")
    set_default("/data/server/php-8.0")
    after_check(function(option)
        local vendor_php_includes, _ = os.iorun("$(vendor-php)/bin/php-config --includes")
        local vendor_php_libs, _ = os.iorun("$(vendor-php)/bin/php-config --libs")
        option:add("cxflags", vendor_php_includes)
        option:add("ldflags", vendor_php_libs)
    end)
    
option("vendor-phpext")
    add_deps("vendor-php")
    set_default("/data/vendor/phpext-4.0")
    add_links("phpext")
    after_check(function(option)
        option:add("includedirs", "$(vendor-phpext)/include")
        option:add("linkdirs","$(vendor-phpext)/lib")
    end)

option("vendor-curl")
    set_default("/data/vendor/curl-7.71")
    add_includedirs("$(vendor-curl)/include")
    after_check(function(option)
        local vendor_curl_libs, _ = os.iorunv("pkg-config", {"libcurl", "--libs"}, {envs = {PKG_CONFIG_PATH=option:value().."/lib/pkgconfig"}})
        option:add("ldflags", vendor_curl_libs:trim())
    end)

option("vendor-fmt")
    set_default("/data/vendor/fmt-7.0")
    add_links("fmt")
    after_check(function(option)
        option:add("includedirs","$(vendor-fmt)/include")
        option:add("linkdirs","$(vendor-fmt)/lib")
    end)

target("core")
    add_rules("mode.debug")
    set_kind("shared")
    add_files("src/core/*.cpp","src/core/extension/*.cpp")
    add_options("vendor-boost")
    add_links("boost_context", "boost_system")
    add_options("vendor-php")
    add_options("vendor-phpext")
    add_options("vendor-curl")
    add_options("vendor-fmt")
    add_links("pthread")
    set_filename("flame-core.so")
    on_install(function(target)
        local vendor_php_extension_dir, _ = os.iorun("$(vendor-php)/bin/php-config --extension-dir")
        local vendor_php_include_dir, _ = os.iorun("$(vendor-php)/bin/php-config --include-dir")
        vendor_php_extension_dir = vendor_php_extension_dir:trim()
        vendor_php_include_dir = vendor_php_include_dir:trim() .. "/ext/flame/core"
        cprint("${bright green}install extension to ${clear}'%s' ...", vendor_php_extension_dir)
        os.cp(target:targetfile(), vendor_php_extension_dir)

        cprint("${bright green}install header files to ${clear}'%s' ...", vendor_php_include_dir)
        os.mkdir(vendor_php_include_dir)
        os.cp("src/core/*.hpp", vendor_php_include_dir)
    end)

target("core-test")
    add_rules("mode.debug")
    set_kind("binary")
    add_files("src/core/*.cpp", "tests/core/*.cpp")
    add_options("vendor-boost")
    add_links("boost_unit_test_framework", "boost_context", "boost_system")
    add_options("vendor-curl")
    add_options("vendor-fmt")
    add_links("pthread")
    on_install(function(target)
        -- 测试，无安装目标
    end)